### ISSUE TITLE
Gestion des commandes (Accueil)

### ISSUE THREAD

**Issue by Mounia-kazi** [soufianeEurequat/vente_embarquee#9]
Corriger les mots "Générer facture" "Générer livraison" et "détails" dans l'entête du tableau et dans les boutons en bas ainsi que le mot "début" en bas.

**Comment by soufianeEurequat** [comment]
c'est fait

**Comment by Mounia-kazi** [comment]
Il reste le mot "début" et le mot "État" que j'avais oublié de noter.

**Comment by soufianeEurequat** [comment]
c'est fait
